name: "Build Custom OpenWrt Installer ISO"

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '请输入下载地址(扩展名 .img.gz/.img.xz/.img.zip)'
        required: true
        default: 'https://default.example.com/file.img.gz'

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: |
          chmod +x "${{ github.workspace }}/custom.sh"
          chmod +x "${{ github.workspace }}/supportFiles/custom/build.sh"

      - name: "Build Image"
        run: |
          download_url="${{ github.event.inputs.download_url }}"
          ./custom.sh "$download_url"

      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "Custom-Installer-x86_64-ISO"
          body_path: "${{ github.workspace }}/supportFiles/custom/info.md"
          files: |
            output/custom-installer-x86_64.iso
          token: "${{ secrets.GITHUB_TOKEN }}"
